### PR TITLE
OSOE-49: Enforce Windows newlines for C# files to avoid false positives with IDE0055 warning.

### PR DESCRIPTION
**Pull request by sarahelsaig**
OSOE-49

### CODE REVIEW

**Review by Piedone — APPROVED** [review]

**Review by Piedone — CHANGES_REQUESTED** [review]
With the current SDK, [OCC-3: Fix linux-specific problems in Lombiq.Analyzers. by DAud-IcI · Pull Request #53 · Lombiq/.NET-Analyzers](https://github.com/Lombiq/.NET-Analyzers/pull/53/files#diff-2dde510688211f1479ac8bbd63641430561100e5ac6b5e50f6e8821a9322bfb9)  shouldn’t be needed, this is why I removed it under [Removing now unneeded Microsoft.Net.Compilers.Toolset reference · Lombiq/.NET-Analyzers@52016af](https://github.com/Lombiq/.NET-Analyzers/commit/52016af07c3ce298ccc2d3a2a26725f14457a746).

**Comment by sarahelsaig** [comment]
That wasn't my experience, that's why I have added it back. What do you mean by "current" exactly?

**Comment by Piedone** [comment]
\>=6.0.202, see https://github.com/dotnet/sdk/issues/23972

**Comment by sarahelsaig** [comment]
That explains it, I had "6.0.102" installed on my Linux desktop. But if we have a specific minimum version requirement within the same major version that really should be documented.

**Comment by Piedone** [comment]
I'd give us (me) a pass here, since it was a workaround for a .NET SDK bug they introduced with a patch version :D.

**Comment by sarahelsaig** [comment]
Anyway, we shouldn't remove the fix at least until May 22, because [6.0.200's lifecycle is still active](https://docs.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs#:~:text=Jul%20'23-,6.0.200,-17.1).

**Comment by Piedone** [comment]
In principle I agree, I'd just really dread to re-add this workaround for these 9 days and have to keep in mind to remove it and retest everything.

**Comment by sarahelsaig** [comment]
Even after may 22, it's not like everyone will instantly and magically switch over to the latest SDK. Why are you so eager to break backwards compatibility? Does this fix have any serious drawbacks?

**Comment by Piedone** [comment]
Yeah, but we can still say we don't support older SDKs.

This is a risky workaround because it makes us use the compiler from NuGet instead of the SDK, which is unexpected and discouraged in [the package Readme](https://www.nuget.org/packages/Microsoft.Net.Compilers.Toolset/) too. It's a hack that we shouldn't keep until absolutely necessary, hence me also jumping on removing it the first time this was possible.

**Comment by sarahelsaig** [comment]
> Yeah, but we can still say we don't support older SDKs.

I suppose we can say that. (I'm not happy about it tho.) Yet the main problem is that we didn't say anything, which confused the person I least want to see confused: myself. :D  Instead of deleting the code, I'm going to comment it out and add some text indicating that  SDK versions prior to 6.0.102 have to uncomment it.

**Comment by Piedone** [comment]
I'm sorry :(. Sure! prior to 202, though.

**Review by Piedone — APPROVED** [review]

**Review by Piedone — APPROVED** [review]

**Review by 0liver — APPROVED** [review]

**Pull request merged**
